[project]
authors = ["Hydrogen-labs"]
entry = "main.sw"
license = "Apache-2.0"
name = "mock-stork-contract"

[dependencies]
libraries = { path = "../../libraries" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }

[proxy]
enabled = true
